//! Generated by dx-compiler (Macro Mode)
//! DO NOT EDIT - This file is automatically generated

#![no_std]
#![no_main]

#[panic_handler]
fn panic(_: &core::panic::PanicInfo) -> ! {
    unsafe { core::arch::wasm32::unreachable() }
}

// ============================================================================
// FFI: JavaScript Host Functions (HTIP Protocol)
// ============================================================================

extern "C" {
    /// Clone template by ID, returns node handle
    fn host_clone_template(template_id: u32) -> u32;
    /// Append child to parent
    fn host_append(parent_id: u32, child_id: u32);
    /// Set text by slot ID
    fn host_patch_slot(node_id: u32, slot_id: u32, ptr: *const u8, len: u32);
    /// Queue render batch
    fn host_flush_render();
    /// Get shared memory pointer
    fn host_get_shared_buffer() -> *mut u8;
}

// ============================================================================
// Template IDs
// ============================================================================

const TEMPLATE_0: u32 = 0;

/// State for Dashboard component
#[repr(C)]
pub struct DashboardState {
    pub users: i32,
    pub loading: bool,
    pub error: i32,
    pub selectedUser: i32,
    pub searchQuery: &'static str,
    pub sortOrder: &'static str,
    pub filterStatus: &'static str,
}

impl Default for DashboardState {
    fn default() -> Self {
        Self {
            users: 0,
            loading: true,
            error: 0,
            selectedUser: 0,
            searchQuery: "",
            sortOrder: "asc",
            filterStatus: "all",
        }
    }
}

/// State for Header component
#[repr(C)]
pub struct HeaderState {
    pub users: i32,
    pub loading: bool,
    pub error: i32,
    pub selectedUser: i32,
    pub searchQuery: &'static str,
    pub sortOrder: &'static str,
    pub filterStatus: &'static str,
}

impl Default for HeaderState {
    fn default() -> Self {
        Self {
            users: 0,
            loading: true,
            error: 0,
            selectedUser: 0,
            searchQuery: "",
            sortOrder: "asc",
            filterStatus: "all",
        }
    }
}

/// State for Sidebar component
#[repr(C)]
pub struct SidebarState {
    pub users: i32,
    pub loading: bool,
    pub error: i32,
    pub selectedUser: i32,
    pub searchQuery: &'static str,
    pub sortOrder: &'static str,
    pub filterStatus: &'static str,
}

impl Default for SidebarState {
    fn default() -> Self {
        Self {
            users: 0,
            loading: true,
            error: 0,
            selectedUser: 0,
            searchQuery: "",
            sortOrder: "asc",
            filterStatus: "all",
        }
    }
}

/// State for SearchBar component
#[repr(C)]
pub struct SearchBarState {
    pub users: i32,
    pub loading: bool,
    pub error: i32,
    pub selectedUser: i32,
    pub searchQuery: &'static str,
    pub sortOrder: &'static str,
    pub filterStatus: &'static str,
}

impl Default for SearchBarState {
    fn default() -> Self {
        Self {
            users: 0,
            loading: true,
            error: 0,
            selectedUser: 0,
            searchQuery: "",
            sortOrder: "asc",
            filterStatus: "all",
        }
    }
}

/// State for FilterBar component
#[repr(C)]
pub struct FilterBarState {
    pub users: i32,
    pub loading: bool,
    pub error: i32,
    pub selectedUser: i32,
    pub searchQuery: &'static str,
    pub sortOrder: &'static str,
    pub filterStatus: &'static str,
}

impl Default for FilterBarState {
    fn default() -> Self {
        Self {
            users: 0,
            loading: true,
            error: 0,
            selectedUser: 0,
            searchQuery: "",
            sortOrder: "asc",
            filterStatus: "all",
        }
    }
}

/// State for LoadingSpinner component
#[repr(C)]
pub struct LoadingSpinnerState {
    pub users: i32,
    pub loading: bool,
    pub error: i32,
    pub selectedUser: i32,
    pub searchQuery: &'static str,
    pub sortOrder: &'static str,
    pub filterStatus: &'static str,
}

impl Default for LoadingSpinnerState {
    fn default() -> Self {
        Self {
            users: 0,
            loading: true,
            error: 0,
            selectedUser: 0,
            searchQuery: "",
            sortOrder: "asc",
            filterStatus: "all",
        }
    }
}

/// State for ErrorBanner component
#[repr(C)]
pub struct ErrorBannerState {
    pub users: i32,
    pub loading: bool,
    pub error: i32,
    pub selectedUser: i32,
    pub searchQuery: &'static str,
    pub sortOrder: &'static str,
    pub filterStatus: &'static str,
}

impl Default for ErrorBannerState {
    fn default() -> Self {
        Self {
            users: 0,
            loading: true,
            error: 0,
            selectedUser: 0,
            searchQuery: "",
            sortOrder: "asc",
            filterStatus: "all",
        }
    }
}

/// State for UserTable component
#[repr(C)]
pub struct UserTableState {
    pub users: i32,
    pub loading: bool,
    pub error: i32,
    pub selectedUser: i32,
    pub searchQuery: &'static str,
    pub sortOrder: &'static str,
    pub filterStatus: &'static str,
}

impl Default for UserTableState {
    fn default() -> Self {
        Self {
            users: 0,
            loading: true,
            error: 0,
            selectedUser: 0,
            searchQuery: "",
            sortOrder: "asc",
            filterStatus: "all",
        }
    }
}

/// State for UserDetail component
#[repr(C)]
pub struct UserDetailState {
    pub users: i32,
    pub loading: bool,
    pub error: i32,
    pub selectedUser: i32,
    pub searchQuery: &'static str,
    pub sortOrder: &'static str,
    pub filterStatus: &'static str,
}

impl Default for UserDetailState {
    fn default() -> Self {
        Self {
            users: 0,
            loading: true,
            error: 0,
            selectedUser: 0,
            searchQuery: "",
            sortOrder: "asc",
            filterStatus: "all",
        }
    }
}

/// State for Footer component
#[repr(C)]
pub struct FooterState {
    pub users: i32,
    pub loading: bool,
    pub error: i32,
    pub selectedUser: i32,
    pub searchQuery: &'static str,
    pub sortOrder: &'static str,
    pub filterStatus: &'static str,
}

impl Default for FooterState {
    fn default() -> Self {
        Self {
            users: 0,
            loading: true,
            error: 0,
            selectedUser: 0,
            searchQuery: "",
            sortOrder: "asc",
            filterStatus: "all",
        }
    }
}

// ============================================================================
// Slot Bindings
// ============================================================================

const SLOT_0: u32 = 0; // <- searchQuery
const SLOT_1: u32 = 1; // <- setSearchQuery
const SLOT_2: u32 = 2; // <- filterStatus
const SLOT_3: u32 = 3; // <- setFilterStatus
const SLOT_4: u32 = 4; // <- sortOrder
const SLOT_5: u32 = 5; // <- setSortOrder
const SLOT_6: u32 = 6; // <- loading && <LoadingSpinner />
const SLOT_7: u32 = 7; // <- error && <ErrorBanner message={error
const SLOT_8: u32 = 8; // <- filteredUsers
const SLOT_9: u32 = 9; // <- setSelectedUser
const SLOT_10: u32 = 10; // <- selectedUser
const SLOT_11: u32 = 11; // <- selectedUser && (                      <UserDetail
const SLOT_12: u32 = 12; // <- () => setSelectedUser(null)

// ============================================================================
// WASM Exports
// ============================================================================

#[no_mangle]
pub extern "C" fn init() -> u32 {
    // Initialize shared buffer
    unsafe {
        let _shared = host_get_shared_buffer();
    }
    0 // Success
}

/// Initial render - clone templates and set up DOM
#[no_mangle]
pub extern "C" fn render() {
    unsafe {
        let node_0 = host_clone_template(TEMPLATE_0);
        host_append(0, node_0);
        host_flush_render();
    }
}

/// Update DOM with current state values
#[no_mangle]
pub extern "C" fn update() {
    unsafe {
        // Read from shared buffer and patch slots
        // Patch slot 0 with searchQuery
        // host_patch_slot(node_id, SLOT_0, SEARCHQUERY_PTR, SEARCHQUERY_LEN);
        // Patch slot 1 with setSearchQuery
        // host_patch_slot(node_id, SLOT_1, SETSEARCHQUERY_PTR, SETSEARCHQUERY_LEN);
        // Patch slot 2 with filterStatus
        // host_patch_slot(node_id, SLOT_2, FILTERSTATUS_PTR, FILTERSTATUS_LEN);
        // Patch slot 3 with setFilterStatus
        // host_patch_slot(node_id, SLOT_3, SETFILTERSTATUS_PTR, SETFILTERSTATUS_LEN);
        // Patch slot 4 with sortOrder
        // host_patch_slot(node_id, SLOT_4, SORTORDER_PTR, SORTORDER_LEN);
        // Patch slot 5 with setSortOrder
        // host_patch_slot(node_id, SLOT_5, SETSORTORDER_PTR, SETSORTORDER_LEN);
        // Patch slot 6 with loading && <LoadingSpinner />
        // host_patch_slot(node_id, SLOT_6, LOADINGLOADINGSPINNER_PTR, LOADINGLOADINGSPINNER_LEN);
        // Patch slot 7 with error && <ErrorBanner message={error
        // host_patch_slot(node_id, SLOT_7, ERRORERRORBANNERMESSAGEERROR_PTR, ERRORERRORBANNERMESSAGEERROR_LEN);
        // Patch slot 8 with filteredUsers
        // host_patch_slot(node_id, SLOT_8, FILTEREDUSERS_PTR, FILTEREDUSERS_LEN);
        // Patch slot 9 with setSelectedUser
        // host_patch_slot(node_id, SLOT_9, SETSELECTEDUSER_PTR, SETSELECTEDUSER_LEN);
        // Patch slot 10 with selectedUser
        // host_patch_slot(node_id, SLOT_10, SELECTEDUSER_PTR, SELECTEDUSER_LEN);
        // Patch slot 11 with selectedUser && (                      <UserDetail
        // host_patch_slot(node_id, SLOT_11, SELECTEDUSERUSERDETAILUSERSELECTEDUSER_PTR, SELECTEDUSERUSERDETAILUSERSELECTEDUSER_LEN);
        // Patch slot 12 with () => setSelectedUser(null)
        // host_patch_slot(node_id, SLOT_12, SETSELECTEDUSERNULL_PTR, SETSELECTEDUSERNULL_LEN);
        host_flush_render();
    }
}

/// Event dispatcher - called by JS with event ID
#[no_mangle]
pub extern "C" fn on_event(id: u32) {
    match id {
        _ => {}
    }
}